import { FC, ReactNode } from 'react';

import Footer from './Footer/Footer';
import Header from './Header/Header';
import LocalizationProvider from '@/context/localization.context';
import { Color } from '@/types/enums';

interface IRootLayout {
  children: ReactNode;
  themeColor: Color;
}
// export const metadata: Metadata = {
//   title: 'Super Груп | Надихати людей',
//   description: 'Generated by create next app',
// };

const RootLayout: FC<IRootLayout> = ({ data, children, themeColor }) => {
  console.log('🚀 ~ data:', data);
  return (
    <LocalizationProvider homePage={data}>
      <div className='overflow-clip'>
        <Header themeColor={themeColor} />
        <main>{children}</main>
        <Footer />
      </div>
    </LocalizationProvider>
  );
};
export default RootLayout;

// const RootLayout: FC<IRootLayout> = ({ children, themeColor }) => {
//   return (
//     <div className='overflow-clip'>
//       <Header themeColor={themeColor} />
//       <main>{children}</main>
//       <Footer />
//     </div>
//   );
// };
// export default RootLayout;
