import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import '../styles/globals.scss';

const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Сімпатік Груп | Надихати людей',
  description: 'Generated by create next app',
};

const RootLayoutPage = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='uk'>
      <head>
        <link
          rel='icon'
          type='image/png'
          href='/favicon/favicon-96x96.png'
          sizes='96x96'
        />
        <link rel='icon' type='image/svg+xml' href='/favicon/favicon.svg' />
        <link rel='shortcut icon' href='/favicon/favicon.ico' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/favicon/apple-touch-icon.png'
        />
        <link rel='manifest' href='/favicon/site.webmanifest' />
        <link rel='icon' href='/favicon/favicon.svg' type='image/svg+xml' />
      </head>
      <body className={`${raleway.className} `}>{children}</body>
    </html>
  );
};

export default RootLayoutPage;
