import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

import './globals.scss';

const raleway = Raleway({
  subsets: ['cyrillic', 'latin'],
  weight: ['400', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Сімпатік Груп | Надихати людей',
  description: 'Generated by create next app',
};

const RootLayoutPage = ({
  children,
  color,
}: Readonly<{
  children: React.ReactNode;
  color: 'dark' | 'white';
}>) => {
  return (
    <html lang='uk'>
      <body className={raleway.className}>{children}</body>
    </html>
  );
};

export default RootLayoutPage;
