name: Deploy NextJS

on:
  push:
    branches:
      - main  # Запускати workflow при пушах до гілки main
      - dev   # Запускати workflow при пушах до гілки dev

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Виконання команд на сервері
      - name: Deploy on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          password: ${{ secrets.PROD_SSH_PASSWORD }}
          script: |
            echo "Stopping NextJS application..."
            echo "${{ secrets.PROD_SSH_PASSWORD }}" | sudo -S systemctl stop nextjs

            cd /home/max/simpatik.group || exit

            echo "Pulling latest version from Git..."
            git pull

            echo "Resetting to specific commit ${{ github.sha }}..."
            git reset --hard ${{ github.sha }}

            echo "Installing dependencies..."
            npm install -y

            echo "Building project..."
            npm run build

            echo "Starting NextJS application..."
            echo "${{ secrets.PROD_SSH_PASSWORD }}" | sudo -S systemctl start nextjs

            echo "Production deployment completed!"

  deploy-development:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      # Клонування репозиторію
      - name: Checkout repository
        uses: actions/checkout@v4

      # Виконання команд на сервері
      - name: Deploy on development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          script: |
            echo "Stopping NextJS application..."
            echo "${{ secrets.DEV_SSH_PASSWORD }}" | sudo -S systemctl stop nextjs

            cd /home/max/simpatik.group || exit

            echo "Checking out dev branch..."
            git fetch origin dev
            git checkout dev

            echo "Pulling latest version from Git..."
            git pull origin dev

            echo "Resetting to specific commit ${{ github.sha }}..."
            git reset --hard ${{ github.sha }}

            echo "Installing dependencies..."
            npm install -y

            echo "Building project..."
            npm run build

            echo "Starting NextJS application..."
            echo "${{ secrets.DEV_SSH_PASSWORD }}" | sudo -S systemctl start nextjs

            echo "Development deployment completed!"

